# Generated by Django 3.2 on 2021-09-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
