# Generated by Django 3.2 on 2021-10-22 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0004_auto_20211020_1843'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
    ]
