# Generated by Django 5.2.10 on 2026-06-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0004_alter_librarydata_commitments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bfsimport',
            name='available',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='beginning_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='contributions',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='ending_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='expenditures',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='foundation_transfers',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='gift_fee_payments',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='investment_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='market_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='principal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='projected_income',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='real_gl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='transfers_adj',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='transfers_to_univ',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='unavailable',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bfsimport',
            name='unreal_gl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='librarydata',
            name='commitments',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='librarydata',
            name='max_mtf_trf_amt',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='librarydata',
            name='operating_balance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='librarydata',
            name='projected_annual_income',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='librarydata',
            name='total_balance',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='librarydata',
            name='total_fund_value',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='librarydata',
            name='ytd_appropriation',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='librarydata',
            name='ytd_expenditure',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
