# Generated by Django 5.2.14 on 2026-07-17 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0005_alter_bfsimport_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=6)),
                ('cost_center', models.CharField(max_length=2)),
                ('fund', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('fund_purpose', models.TextField(blank=True)),
                ('fund_summary', models.TextField(blank=True)),
                ('fund_restriction', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('lbs_notes', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funds_manager', to='ge.gestaff')),
                ('mtf_authority', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='funds_authority', to='ge.gestaff')),
            ],
        ),
    ]
