# Generated by Django 5.2.14 on 2026-07-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0006_gestaff_geunit_gefund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gefund',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funds_manager', to='ge.gestaff'),
        ),
        migrations.AlterField(
            model_name='gefund',
            name='mtf_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funds_authority', to='ge.gestaff'),
        ),
    ]
