# Generated by Django 5.2.14 on 2026-08-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0007_alter_gefund_manager_alter_gefund_mtf_authority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gefund',
            options={'verbose_name_plural': 'GE Funds'},
        ),
        migrations.AlterModelOptions(
            name='gestaff',
            options={'verbose_name_plural': 'GE Staff'},
        ),
        migrations.AlterModelOptions(
            name='geunit',
            options={'verbose_name_plural': 'GE Units'},
        ),
        migrations.AddField(
            model_name='gefund',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ge.geunit'),
        ),
        migrations.CreateModel(
            name='GeRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('aul', 'AUL'), ('head', 'Head')], max_length=100)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.gestaff')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ge.geunit')),
            ],
            options={
                'verbose_name_plural': 'GE Recipients',
            },
        ),
        migrations.AddField(
            model_name='geunit',
            name='members',
            field=models.ManyToManyField(through='ge.GeRecipient', to='ge.gestaff'),
        ),
    ]
