# Generated by Django 5.2.14 on 2026-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0008_alter_gefund_options_alter_gestaff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gefund',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gefund',
            name='home_unit_dept',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gefund',
            name='projected_annual_income',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='gefund',
            name='manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gefund',
            name='mtf_authority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
