# Generated by Django 5.2.14 on 2026-08-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0009_gefund_active_gefund_home_unit_dept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gefund',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gefund',
            name='mtf_authority',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
