# Generated by Django 5.2.14 on 2026-08-20 23:02

from django.db import migrations


def migrate_staff_names_to_fund_fields(apps, schema_editor) -> None:
    """Copy staff names from `GeStaff` records into specific `GeFund` fields,
    replacing the previous values which are string-ified `GeStaff.id`s.

    :param apps: Django apps registry.
    :param schema_editor: Django schema editor.
    """

    # To collect funds for bulk update later
    funds_to_update = []
    GeFund = apps.get_model("ge", "GeFund")
    GeStaff = apps.get_model("ge", "GeStaff")
    for fund in GeFund.objects.all():
        # Set manager and mtf_authority to the full name value from the
        # corresponding `GeStaff` record, based on the current id values
        # stored in those fields from when they were foreign keys.
        fund.manager = GeStaff.objects.get(pk=int(fund.manager)).name
        fund.mtf_authority = GeStaff.objects.get(pk=int(fund.mtf_authority)).name
        funds_to_update.append(fund)

    GeFund.objects.bulk_update(
        funds_to_update,
        ["manager", "mtf_authority"],
        batch_size=1000,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("ge", "0010_alter_gefund_manager_alter_gefund_mtf_authority"),
    ]

    operations = [
        # Run our custom data update, with no way to reverse it.
        migrations.RunPython(
            migrate_staff_names_to_fund_fields, migrations.RunPython.noop
        )
    ]
