# Generated by Django 5.2.14 on 2026-08-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0011_update_fund_with_staff_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gefund',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
