# Generated by Django 5.2.14 on 2026-09-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0012_alter_gefund_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gefund',
            options={'verbose_name': 'GE Fund', 'verbose_name_plural': 'GE Funds'},
        ),
        migrations.AlterModelOptions(
            name='gerecipient',
            options={'verbose_name': 'GE Recipient', 'verbose_name_plural': 'GE Recipients'},
        ),
        migrations.AlterModelOptions(
            name='gestaff',
            options={'verbose_name': 'GE Staff', 'verbose_name_plural': 'GE Staff'},
        ),
        migrations.AlterModelOptions(
            name='geunit',
            options={'verbose_name': 'GE Unit', 'verbose_name_plural': 'GE Units'},
        ),
    ]
