# Generated by Django 5.2.17 on 2026-10-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ge', '0013_alter_gefund_options_alter_gerecipient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gefund',
            name='fund_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
