# Generated by Django 3.2 on 2021-10-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0002_staff_staff_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
