# Generated by Django 3.2 on 2021-10-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0003_alter_staff_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
    ]
