# Generated by Django 3.2.5 on 2021-10-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0005_auto_20211022_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='role',
            field=models.CharField(choices=[('aul', 'AUL'), ('head', 'Head')], max_length=100),
        ),
    ]
