# Generated by Django 4.2.16 on 2024-12-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qdb', '0009_alter_recipient_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.CharField(default='0', max_length=20)),
                ('hours', models.CharField(default='0', max_length=20)),
                ('days_of_month', models.CharField(default='1', max_length=20)),
                ('months', models.CharField(default='1', max_length=20)),
                ('days_of_week', models.CharField(default='*', max_length=20)),
                ('command', models.CharField(default="echo 'Hello' >> /tmp/cron.log 2>&1", max_length=100)),
                ('enabled', models.BooleanField(default=False)),
                ('permanent_id', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
