name: Build and Test LBS
on: 
  pull_request:
  workflow_dispatch:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build the stack
        run: docker-compose -f docker-compose.ga.yml up --build -d
      
      - name: Wait for database
        run: sleep 15s
        shell: bash

      - name: What version
        run: docker-compose --version

      - name: Containers
        run: docker-compose ps

      - name: Top processes
        run: docker-compose top

      - name: Show environment - debugging
        run: docker-compose exec -T django env
        continue-on-error: true

      - name: Show migrations - debugging
        run: docker-compose exec -T django python lbs/manage.py showmigrations
      
      - name: Create models
        run: docker-compose exec -T django python lbs/manage.py migrate
      
      - name: Load data
        run: docker-compose exec -T django python lbs/manage.py load_initial_data lbs/qdb/fixtures/staff.csv lbs/qdb/fixtures/unit.csv lbs/qdb/fixtures/accounts.csv
      
      - name: Check connectivity
        #run: docker run --network container:django-frontend appropriate/curl -s -I http://localhost:8000/admin/
        run: curl -s -I http://localhost:8000/admin/
      
      - name: Run tests
        # -T to disable TTY allocation
        run: docker-compose exec -T django python lbs/manage.py test qdb
