name: Build LBS
on: 
  push:
    branches:
      - 'SYS-705/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Run tests
        run: docker-compose exec django python lbs/manage.py test qdb
